# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_auto_20170909_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='born_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
