# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_auto_20170909_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
