# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0011_auto_20170920_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.Cities'),
        ),
    ]
